### ISSUE TITLE
Исправить межосевое расстояние подающих шестерен

### ISSUE THREAD

**Issue by DeltaDesignRus** [dmitry-sorkin/BeMeGe#1]
Измерения сняты микрометром, шестерни вращались, чтобы поймать максимум по зубцам.
![2021-09-02 23 00 40](https://user-images.githubusercontent.com/19409260/131895249-0def3366-d4b6-4447-a225-9e28cd511441.jpg)
Исходя из этих измерений, и зная, что цилиндрическая (гладкая) часть тела подающей шестерни имеет диаметр 8мм (по измерениям 7.99мм), а так же зная межосевое расстояние можно вычислить зазор между цилиндрическими поверхностями - он составляет 0.6мм.
В связи с этим, нужно нарастить часть корпуса, к которой прилегает шестерня рычага, устранив зазор между корпусом и шестерней полностью.

**Comment by DeltaDesignRus** [comment]
Возможно стоит сместить шестерню в рычаге, чтобы в закрытом состоянии внешняя поверхность рычага осталась параллельной корпусу.

**Comment by dmitry-sorkin** [comment]
Исправлено в #2
